version: "3"
services:
  backend:
    build: "."
    working_dir: "/workspace/go-grpc-sample"
    command: sleep infinity
    ports:
      - 9000:9000
    volumes:
      - ../:/workspace/go-grpc-sample
    environment:
      PORT: 9000
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_HOST: "database"
      DB_NAME: "sample"
      DB_PORT: "5432"
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: sample
      POSTGRES_PORT: 5432
      TZ: "Asia/Tokyo"
